# Docker compose file for Nginx Reverse Proxy with SSL termination
version: '3.6'

services:
    proxy:
        build: "./"
        restart: always
        # hostname: www.ele-net.de
        ports:
            - "80:80"
            # - "443:443"
        networks:
            - default
            - dmz_net
networks:
    dmz_net:
        external: true
