# Docker compose file for Nginx Reverse Proxy with SSL termination
version: '3.6'

services:
    proxy:
        build: "./"
        restart: always
        volumes: 
            - certs:/etc/letsencrypt
        ports:
            - "80:80"
            - "443:443"
            - "4434:4434"
        networks:
            - default
            - dmz_net
networks:
    dmz_net:
        external: true

volumes:
    certs:
